//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERTS.Core.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participant
    {
        public string TeamName { get; set; }
        public int StudentId { get; set; }
        public int EventNumber { get; set; }
    
        public virtual Team Team { get; set; }
        public virtual Student Student { get; set; }
        public virtual Event Event { get; set; }
    }
}
